spring:
  application:
    name: open-game-backend-matchmaking

server:
  port: 9002

de:
  opengamebackend:
    application:
      version: @project.version@

logging:
  level:
    org.zalando.logbook: TRACE
